services:
  postgres:
    image: postgres:16-alpine
    container_name: game-math-postgres-dev
    environment:
      POSTGRES_DB: game_math
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    container_name: game-math-server-dev
    depends_on:
      - postgres
    environment:
      NODE_ENV: development
      PORT: 4000
      CORS_ORIGIN: http://localhost:3000
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/game_math?schema=public
      JWT_SECRET: dev-docker-jwt-secret-change-me-in-real-deploy
    ports:
      - "4000:4000"
    volumes:
      - ./server:/app
      - /app/node_modules

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    container_name: game-math-client-dev
    depends_on:
      - server
    environment:
      NEXT_PUBLIC_API_BASE_URL: http://localhost:4000
      CHOKIDAR_USEPOLLING: "true"
      WATCHPACK_POLLING: "true"
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
      - /app/.next

volumes:
  postgres_data:

